signin/urls.py
from django.urls import path

from . import views  

app_name = 'signin'

urlpatterns = [
    path('', views.login_view, name='ajax_login'),
    path('home/', views.home, name='home'),
]

scraper/models.py
from django.db import models

# Create your models here.

signin/models.py
from django.db import models

# Create your models here.

scraper/views.py
from django.shortcuts import render

# Create your views here.

signin/views.py
from django.shortcuts import render
from django.http import JsonResponse

# Create your views here.

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from asgiref.sync import sync_to_async

from signin import hub

async def login_view(request):
    if request.method == "GET":
        print('desoues de get')
        return render(request, 'signin/login.html')
    
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = await sync_to_async(authenticate)(request, username=username, password=password)
        print('despues de else')
        if user is not None:
            await sync_to_async(login)(request, user)
            return render(request, 'signin/home.html')
        else:
            return HttpResponse("Invalid username or password.")

async def home():
    results = await hub.main('', '')
    data = {'results': results}  
    return JsonResponse(data)

signin/templates/signin/home.html
<html>
    {% load static %}

    <head>
        <title>prealpha-1.0</title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div id="theme-switcher">
            <button id="switch_theme">Switch theme</button>
        </div>
        <!-- llama loading html -->
        {% include 'signin/loading.html' %}
        <!-- Contenido de datos que se mostrarán después de cargarlos -->
        <div class="content" style="background-color: #40bb2a;" id="json">
            {% for result in data.results %}
                <!-- Mostrar datos aquí -->
                <p>{{ result }}</p>
            {% endfor %}
        </div>
        
        <script>
            var theme = localStorage.getItem('theme') || 'light'; // default to light

            var switchTheme = function() {
              theme = theme === 'dark' ? 'light' : 'dark';
              localStorage.setItem('theme', theme);
              document.documentElement.setAttribute("data-theme", theme);
            }
          
            document.getElementById('switch_theme').addEventListener('click', function() {
              switchTheme();
            });
          
            switchTheme();
        </script>
        <script>
            // Función para cargar los datos de 'home(request)' en segundo plano
            async function cargarDatos() {
                try {
                    const response = await fetch('home/');
                    const data = await response.text();
                    // Actualiza el contenido de 'home-content' con el resultado de 'home/'
                    const homeContent = document.getElementById('json');
                    homeContent.innerHTML = data;
                    // Procesa los datos y actualiza la página según sea necesario
                    // Modifica el texto a "Datos cargados"
                    const loadingText = document.getElementById('loading-text');
                    loadingText.textContent = 'Datos cargados';
                    
                    // Oculta el icono de carga
                    const loadingIcon = document.getElementById('loading-icon');
                    loadingIcon.style.display = 'none';
                    
                    // Cambia el color de fondo del contenedor a verde
                    const loadingContainer = document.getElementById('loading_cargandoDatos');
                    loadingContainer.style.backgroundColor = 'black';

                    setTimeout(function() {
                    const content = document.getElementById('loading_cargandoDatos');
                    content.style.display = 'none';
                     }, 6000); // 5000 milisegundos = 5 segundos
                } catch (error) {
                    console.error(error);
                }
            }
        
            // Llama a la función de carga de datos después de que la página se haya cargado
            window.addEventListener('load', cargarDatos);
        </script>
    </body>
</html>

signin/templates/signin/loading.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>prealpha-1.0</title>
    <style>
        /* Estilos CSS para el contenedor de loading */
        .loading-container {
            border-radius: 15px;
            position: fixed;
            top: 90%;
            left: 85%;
            width: 10%;
            height: 6%;
            background-color: rgba(70, 135, 255, 0.8); /* Fondo semitransparente */
            z-index: 1000; /* Asegura que esté en la parte superior */
            display: flex; /* Usar display flex para alinear horizontal y verticalmente */
            align-items: center; /* Centrar verticalmente */
            justify-content: center; /* Centrar horizontalmente */
        }

        /* Estilos CSS para centrar el texto de carga */
        .loading-text {
            font-family: 'Arial';
            text-align: center;
            align-content: center;
            color: white;
            padding: 5px;
            font-size: 15;
        }

        /* Estilos CSS para centrar el icono de carga horizontal y verticalmente */
        .loading-icon {
            /* Estilos para el icono de carga (puedes personalizar estos estilos) */
            border: 4px solid #f3f3f3; /* Círculo exterior */
            border-top: 4px solid #3498db; /* Círculo interior de color */
            border-radius: 50%; /* Hace que el círculo sea redondo */
            width: 10px;
            height: 10px;
            animation: spin 2s linear infinite; /* Agrega una animación de giro */
            margin: 0 auto; /* Centra horizontalmente */
        }

        /* Animación para el giro del icono de carga */
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
    </style>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>
    <div class="loading-container" id="loading_cargandoDatos">
        <div class="loading-icon" id="loading-icon"></div>
        <div class="loading-text" id="loading-text">Cargando datos...</div>
    </div>
</body>
</html>

signin/templates/signin/login.html
<html>
    {% load static %}

    <head>
        <title>prealpha-1.0</title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div id="theme-switcher">
            <button id="switch_theme">Switch theme</button>
        </div>
        <form method="post" hx-post="{% url 'signin:ajax_login' %}" hx-swap="outerHTML">
            {% csrf_token %}
            <label>Username: 
            <input type="text" name="username"></label><br>
            <label>Password: 
            <input type="password" name="password"></label>
            <button type="submit">Login</button>
        </form>
        <script>
            var theme = localStorage.getItem('theme') || 'dark'; // default to light

            var switchTheme = function() {
              theme = theme === 'dark' ? 'light' : 'dark';
              localStorage.setItem('theme', theme);
              document.documentElement.setAttribute("data-theme", theme);
            }
          
            document.getElementById('switch_theme').addEventListener('click', function() {
              switchTheme();
            });
          
            switchTheme();
        </script>
    </body>
</html>